import type { Metadata } from "next";
import { UserRole } from "@/types/user";
import { Sidebar } from "@/components/Sidebar";
import { SIDEBAR_ROUTES } from "@/lib/sidebar-routes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid md:grid-cols-[260px_1fr]">
      <Sidebar basePath="" role={UserRole.USER} routes={SIDEBAR_ROUTES} />

      {children}
    </div>
  );
}
