import type { Metadata } from "next";
import { Sidebar } from "@/components/Sidebar";
import { SIDEBAR_ROUTES } from "@/lib/sidebar-routes";
import { UserRole } from "@/types/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid md:grid-cols-[260px_1fr]">
      <Sidebar
        basePath="/admin"
        role={UserRole.ADMIN}
        routes={SIDEBAR_ROUTES}
      />

      {children}
    </div>
  );
}
